version: '3'

networks:
  app-tier:
    driver: bridge  

services:
  apitododocker:
    build: .
    networks:
      - app-tier
    ports:
      - "3000:3000"
    depends_on:
      - pgsqldb
    volumes:
      - "./:/week11/src/app"

  pgsqldb:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER 
      - POSTGRES_PASSWORD 
      - POSTGRES_DB 
    networks:
      - app-tier
